### ISSUE TITLE
All manifests end up under docker.io path in S3

### ISSUE THREAD

**Issue by com6056** [mcronce/oci-registry#15]
In S3, I only have a `docker.io` path:

<img width="273" alt="image" src="https://github.com/mcronce/oci-registry/assets/5183608/5e66f617-8e6c-4269-a409-becfb2074f45">

If you look in logs too for requests to other registries, it is specifically looking under `docker.io`, even for registries that aren't `docker.io`:
```
crictl pull quay.io/kiwigrid/k8s-sidecar:1.25.1
Image is up to date for quay.io/kiwigrid/k8s-sidecar@sha256:415d07ee1027c3ff7af9e26e05e03ffd0ec0ccf9f619ac00ab24366efe4343bd
```

Results in:
```
oci-registry-5b5495cc57-vbpvb oci-registry 2023-09-29T18:35:36.035138Z  INFO actix_web::middleware::logger: 10.70.134.38 "GET /v2/ HTTP/1.1" 200 0 "-" "cri-o/1.25.4 go/go1.19 os/linux arch/amd64" 0.136317
oci-registry-5b5495cc57-vbpvb oci-registry 2023-09-29T18:35:36.150080Z  WARN oci_registry::api: /kiwigrid/k8s-sidecar/manifests/1.25.1 not found at manifests/docker.io/kiwigrid/k8s-sidecar/1.25.1 in repository (Failed to get object from S3: Service(NoSuchKey("The specified key does not exist."))); pulling from upstream
oci-registry-5b5495cc57-vbpvb oci-registry 2023-09-29T18:35:36.304660Z  INFO actix_web::middleware::logger: 10.70.134.38 "GET /v2/kiwigrid/k8s-sidecar/manifests/1.25.1 HTTP/1.1" 200 3893 "-" "cri-o/1.25.4 go/go1.19 os/linux arch/amd64" 0.267325
oci-registry-5b5495cc57-58ltl oci-registry 2023-09-29T18:35:36.376593Z  WARN oci_registry::api: /kiwigrid/k8s-sidecar/manifests/sha256:f929c7fc94605cd51af74ab7941d7982ce94ab904ea032868026633a3435682a not found at manifests/docker.io/kiwigrid/k8s-sidecar/sha256:f929c7fc94605cd51af74ab7941d7982ce94ab904ea032868026633a3435682a in repository (Failed to get object from S3: Service(NoSuchKey("The specified key does not exist."))); pulling from upstream
oci-registry-5b5495cc57-58ltl oci-registry 2023-09-29T18:35:36.525244Z  INFO actix_web::middleware::logger: 10.70.134.38 "GET /v2/kiwigrid/k8s-sidecar/manifests/sha256:f929c7fc94605cd51af74ab7941d7982ce94ab904ea032868026633a3435682a HTTP/1.1" 200 1624 "-" "cri-o/1.25.4 go/go1.19 os/linux arch/amd64" 0.218926
```

oci-registry version v0.3.20

crio version 1.25.4

Here's my config:
```
data:
  upstream.yaml: |
    - host: registry-1.docker.io
      namespace: docker.io
      password: PASSWORD
      username: USERNAME
    - host: quay.io
      namespace: quay.io
    - host: gcr.io
      namespace: gcr.io
    - host: ghcr.io
      namespace: ghcr.io
    - host: k8s.gcr.io
      namespace: k8s.gcr.io
    - host: registry.k8s.io
      namespace: registry.k8s.io
    - host: public.ecr.aws
      namespace: public.ecr.aws
```
